
export const GET_ALL_HISTORY = "GET_ALL_HISTORY"
export const GET_HISTORY_BY_QUERY = "GET_HISTORY_BY_QUERY"
export const GET_HISTORY_BY_ID = "GETHISTORY_BY_ID"
export const CREATE_HISTORY = "CREATE_HISTORY"
export const UPDATE_HISTORY = "UPDATE_HISTORY"
export const DELETE_HISTORY = "DELETE_HISTORY"

export const GET_ALL_DASHBOARD = "GET_ALL_DASHBOARD"
export const GET_DASHBOARD_BY_ID = "GETDASHBOARD_BY_ID"
export const CREATE_DASHBOARD = "CREATEDASHBOARD"
export const UPDATE_DASHBOARD = "UPDATEDASHBOARD"

export const GET_DASHBOARD_POSTS = "GET_DASHBOARD_POSTS"

export const GET_AUTH = "GET_AUTH"
export const LOGIN = "LOGIN"
export const LOGOUT = "LOGOUT"

export const SIDEBAR_OPEN = "SIDEBAR_OPEN"
export const SIDEBAR_CLOSE = "SIDEBAR_CLOSE"
export const SIDEBAR_TOGGLE = "SIDEBAR_TOGGLE"

export const BIN_OPEN = "BIN_TRUE"
export const BIN_CLOSE = "BIN_CLOSE"

export const UPDATE_TRUE = "UPDATE_TRUE"
export const UPDATE_FALSE = "UPDATE_FALSE"

export const LOGOUT_TRUE = "LOGOUT_TRUE"
export const LOGOUT_FALSE = "LOGOUT_FALSE"

export const TRANSACTION_OPEN = "TRANSACTION_OPEN"
export const TRANSACTION_CLOSE = "TRANSACTION_CLOSE"

export const OPEN_TRUE = "OPEN_TRUE"
export const OPEN_FALSE = "OPEN_FALSE"
export const OPEN_TOGGLE = "OPEN_TOGGLE"

export const DELETE_ID = "DELETE_ID"
export const SEARCH = "SEARCH"

export const HAVEACCOUNT_TRUE = "HAVEACCOUNT_TRUE"
export const HAVEACCOUNT_FALSE = "HAVEACCOUNT_FALSE"
export const HAVEACCOUNT_TOGGLE = "HAVEACCOUNT_TOGGLE"

export const RECEIVE_TRUE = "RECEIVE_TRUE"
export const RECEIVE_FALSE = "RECEIVE_FALSE"
